sem4Projekt/WebApp/Controllers/HelpController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers
{
    [Authorize]
    public class HelpController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

sem4Projekt/WebApp/Controllers/OverviewController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers
{
    [Authorize]
    public class OverviewController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

sem4Projekt/WebApp/Controllers/PrizeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers
{
    [Authorize]
    public class PrizeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

sem4Projekt/WebApp/Controllers/SettingsController.cs
using Microsoft.AspNetCore.Mvc;
using SharedProject;
using SharedProject.Models;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Net.Http.Headers;
using System.Text;
using WebApp.Helpers;
using Microsoft.AspNetCore.Authorization;

namespace WebApp.Controllers
{
    [Authorize]
    public class SettingsController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;

        public SettingsController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        [Route("Partner")]
        public async Task<IActionResult> Partner()
        {
            PartnerModel model = new PartnerModel();
            HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Get, LinkConstants.Api + "Partner/GetAssociatedPartner");

            request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", CookieHelper.GetTokenFromCookie(HttpContext));

            var client = _httpClientFactory.CreateClient();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            var response = await client.SendAsync(request);

            if(!response.IsSuccessStatusCode)
                return View(model);

            var json = await response.Content.ReadAsStringAsync();
            var options = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
            var result = JsonSerializer.Deserialize<PartnerModel>(json, options);

            return View(result);
        }

        [HttpPost]
        [Route("CreatePartner")]
        public async Task<IActionResult> CreatePartner(PartnerModel model)
        {
            HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Post, LinkConstants.Api + "Partner/");

            request.Content = new StringContent(JsonSerializer.Serialize(model), Encoding.UTF8, "application/json");
            request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", CookieHelper.GetTokenFromCookie(HttpContext));

            var client = _httpClientFactory.CreateClient();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            var response = await client.SendAsync(request);

            if (!response.IsSuccessStatusCode)
                return RedirectToAction(nameof(Partner));

            return RedirectToAction(nameof(Partner));
        }

        [HttpPost]
        [Route("UpdatePartner")]
        public async Task<IActionResult> UpdatePartner(PartnerModel model)
        {
            HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Put, LinkConstants.Api + "Partner/" + model.Id);

            request.Content = new StringContent(JsonSerializer.Serialize(model), Encoding.UTF8, "application/json");
            request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", CookieHelper.GetTokenFromCookie(HttpContext));

            var client = _httpClientFactory.CreateClient();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            var response = await client.SendAsync(request);

            if (!response.IsSuccessStatusCode)
                return RedirectToAction(nameof(Partner));

            return RedirectToAction(nameof(Partner));
        }

        [HttpPost]
        [Route("DeletePartner")]
        public async Task<IActionResult> DeletePartner(int id)
        {
            HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Delete, LinkConstants.Partners + id);

            request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", CookieHelper.GetTokenFromCookie(HttpContext));

            var client = _httpClientFactory.CreateClient();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            var response = await client.SendAsync(request);

            if (!response.IsSuccessStatusCode)
                return RedirectToAction(nameof(Partner));

            return RedirectToAction(nameof(Partner));
        }

        [Route("User")]
        public IActionResult User()
        {
            return View();
        }
    }
}

sem4Projekt/WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApp.styles.css" asp-append-version="true" />

    <link rel='stylesheet' href='~/css/main.css'/>
    <link rel='stylesheet' href='~/css/authorization.css'/>
</head>
<body>
    <header>
        <div class='mainNav_img_wrapper'>
            @if(WebApp.Helpers.CookieHelper.CookieAlreadyExists(Context)) {
                <img src='https://avatars.cloudflare.steamstatic.com/f3059f9e1f1482db055fee2a3dced7f7b3e103f0_full.jpg'/>
            }
        </div>
        <nav class='mainNav'>
            @if(WebApp.Helpers.CookieHelper.CookieAlreadyExists(Context))
            {
                <ul>
                    <li><a asp-controller="Overview" asp-action="Index">Oversigt</a></li>
                    <li><a asp-controller="News" asp-action="Index">Nyheder</a></li>
                    <li><a asp-controller="Prize" asp-action="Index">Gevinster</a></li>
                    <li><a asp-controller="Subscription" asp-action="Index">Abonnement</a></li>
                    <li><a asp-controller="Settings" asp-action="Partner">Indstillinger</a></li>
                </ul>
                <ul>
                    <li><a asp-controller="Help" asp-action="Index">Hjælp</a></li>
                    <li><a asp-controller="Authorization" asp-action="Logout">Log Ud</a></li>
                </ul>
            } else
            {
                <ul></ul>
                <ul>
                    <li><a asp-controller="Authorization" asp-action="Register">Registrer</a></li>
                    <li><a asp-controller="Authorization" asp-action="Login">Log Ind</a></li>
                </ul>
            }
        </nav>
    </header>
    <div class="wrapper">
        @RenderBody()
    </div>
    <!--
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>