sem4Projekt/WebApp/Controllers/AuthorizationController.cs
using Microsoft.AspNetCore.Mvc;
using SharedProject;
using SharedProject.Models;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Net.Http.Headers;
using System.Text;
using WebApp.Helpers;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;

namespace WebApp.Controllers
{
    [Route("Auth")]
    public class AuthorizationController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;

        public AuthorizationController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        [Route("Login")]
        public IActionResult Login()
        {
            var model = new LoginModel();
            return View(model);
        }

        [HttpPost]
        [Route("Login")]
        public async Task<IActionResult> Login(LoginModel model)
        {
            HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Post, LinkConstants.Api + "Authentication/Login");

            request.Content = new StringContent(JsonSerializer.Serialize(model), Encoding.UTF8, "application/json");

            var client = _httpClientFactory.CreateClient();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            var response = await client.SendAsync(request);

            if(!response.IsSuccessStatusCode)
                return RedirectToAction(nameof(Login));

            var json = await response.Content.ReadAsStringAsync();
            var options = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
            var result = JsonSerializer.Deserialize<ApiTokenLoginModel>(json, options);

            // Some weird error happened.
            if(result == null)
                return RedirectToAction(nameof(Login));

            // Save token to cookie.
            CookieHelper.SetCookie(HttpContext, result);

            return RedirectToAction("Index", "Home");
        }

        [Route("Register")]
        public IActionResult Register()
        {
            var model = new RegisterModel();
            return View(model);
        }

        [HttpPost]
        [Route("Register")]
        public async Task<IActionResult> Register(RegisterModel model)
        {
            HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Post, LinkConstants.Api + "Authentication/Register");

            request.Content = new StringContent(JsonSerializer.Serialize(model), Encoding.UTF8, "application/json");

            var client = _httpClientFactory.CreateClient();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            var response = await client.SendAsync(request);

            if (response.IsSuccessStatusCode)
                return RedirectToAction(nameof(Login));
            else
                return RedirectToAction(nameof(Register));
        }

        [HttpGet]
        [Route("Logout")]
        public async Task<IActionResult> Logout()
        {
            CookieHelper.RemoveCookie(HttpContext);
            return RedirectToAction("Index", "Home");
        }
    }
}

sem4Projekt/WebApp/Views/Authorization/Login.cshtml
@model SharedProject.Models.LoginModel;
@{
    ViewData["Title"] = "Login";
}

<main class='login_wrapper'>
    <h2 class='login_title'>Partner - Login</h2>
    <img class='login_logo' src='https://avatars.cloudflare.steamstatic.com/f3059f9e1f1482db055fee2a3dced7f7b3e103f0_full.jpg'/>
    <form class='login_form' asp-controller='Authorization' asp-action='Login' method='post'>
        <input class='login_input' asp-for='UserName' placeholder='Email' required/>
        <input class='login_input' asp-for='Password' placeholder='Kodeord' required/>
        <input type='Submit' value='Login'/>
    </form>
    <p class='login_referer'>Ikke allerede medlem? <a asp-controller="Authorization" asp-action="Register">Klik her</a> for at registrere dig.</p>
</main>

sem4Projekt/WebApp/Views/Authorization/Register.cshtml
@model SharedProject.Models.RegisterModel;
@{
    ViewData["Title"] = "Registrer";
}

<main class='register_wrapper'>
    <h2 class='register_title'>Registrering</h2>
    <p class='register_info'>Du er ved at registrere dig som en kommende partner af [REDACTED]. Før du begynder at udfylde dine informationer, bedes du læse vores <a href='#'>Servicevilkår</a>.</p>
    <form class='register_form' asp-controller='Authorization' asp-action='Register' method='post'>
        <input class='register_input' asp-for='UserName' placeholder='Brugernavn' required/>
        <input class='register_input' asp-for='Email' placeholder='Email' required/>
        <input class='register_input' asp-for='Password' placeholder='Kodeord' required/>
        <!--<input class='register_input' type='password' placeholder='Kodeord igen' required/>-->
        <div class='register_tos_wrapper'>
            <p class='register_tos_text'>Jeg bekræfer at have læst og forstået <a href=''>Servicevilkårene</a>.</p>
            <input class='register_tos_checkbox' type='checkbox' required/>
        </div>
        <input type='submit' value='Opret'/>
    </form>
</main>